# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn installBuild
  - yarn installTest
  - cd pmt-win
  - yarn install
  - cd ..

# Post-install test scripts.
test_script:
  - yarn test
  - yarn build
  - cd dist
  - yarn --production install
  - cd ..
  - yarn win
  - npm pack ./dist
  - cd pmt-win
  - yarn build
  - cd ..

# Don't actually build.
build: off

artifacts:
  - path: pmt-win\*.zip
    name: pmt-win

  - path: .\*.tgz
    name: pmt

deploy:
  release: PMT $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: FIafpL9e4Va76x8euAHt8NGF5lJuOUnPuxsVQsWgJrmmUAF5mcfoSPGO68MjlmfE
  artifact: /.*/            # upload all packages to release assets
  draft: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
