# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm run installBuild
  - npm run installTest
  - cd pmt-win
  - npm install
  - cd ..

# Post-install test scripts.
test_script:
  - npm test
  - npm run build
  - cd dist
  - npm --production install
  - cd ..
  - npm run win
  - npm pack dist
  - cd pmt-win
  - npm run build
  - cd ..

# Don't actually build.
build: off

artifacts:
  - path: pmt-win\*.zip
    name: pmt-win

  - path: .\*.tgz
    name: pmt

deploy:
  release: PMT $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: sNwZ6HVVCnYIswT35gP5uPl7CP15B56JvRMniWicIHf/poXfygDQycc/hw+FaBz9
  artifact: /.*/            # upload all packages to release assets
  draft: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
