sudo: required
services:
- docker
language:
- node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm --only=dev install
script:
- npm --production test && npm --production run build
after_success:
- docker build -t $REPO:$COMMIT .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=iide/pmt
  - secure: nVGzC/kr83YuaGL4vLHTr2aYBJ7X9ag93vBiDmMFGmBI3zkLg7gIDSwkWbSQOWoY+lfS9nIHkDA2XwsEsyjksaFAqsKnZRJd+NGgpJoBP2F994WFaPcoRE89jXOBPwKHw8vzHPyRXKCvDPi7de82oQKYV6kDHxzMyd8MVQXKnaZOgjJg9jRP0n30ymD1WeXCyWIHOwwLvBr+DRcMngK+IUozFytqVzS1LXYaZR1qhipOpIwTOQhph5hl8/1F+gug7okmKBNh2GBJNDblp1fqjEk8RCMLvpEUEmnZbokq/zl9YHRFTotdM38AlOZrkdVE21Awj9XePAUUDOPzP6L0S71RWdCrN7Yw/Vt7ITonYea/5BlHiUKvsBJtd9xX+aNG8lP3+0rRSZpIesgHPbigj1OTSEmr6MdgMfoPIUr64N6gbPfMY1BKVo2fB1BnisjKX/yOer+HR3p65EevYTw5M5Y/j/cieEu3o22SXne2IT6UABpRHQ/ByVXzOym1JNA5qlGhu+zbyAZwQvKCZ7/g8ygU06lOiV3IF3IIgvV7bwdm8M2gOuCMUk4kH3qTOxP/40rhoHr/7R/vkn9oExe7C4DzPI3euUC1tR7x/0QnWhIq0UYiOaPOCtB6i7oQirfJ3GYAwZBU+nXDgcNVWH4ODOtnUgo4KWCD5MBPGQS6duo=
  - secure: ml3WRHpcI+aO9neikRGBm6eoKxXeGP3WIhkH7hrwIqC0ssW3VBzvQdyUWrymHFJEh79Mja6ZV7rnh8FAAuKDl82+euK9gJtftLSYkdpjyAyvYX7WCEGoLO7Gkg3abwPXUNJuc2t6GbCuANZGOdZ/Yxxsyqj557A+gdfmPxP/Am3TDSbilCjYxc3Y80DtuPaaF3ytuQ22vSWhDiWZJVmFaR1aL1lCq5xKkFXpoS/VPbf0Vb3/yExUBFj8fywCCNBq4pN6o9K0wcP7Y4jYdZRNhhYOQWQFz4zWz7o4Q//4LeyfcoSwvkIq6dLTluIm/aFZPtJt5BblTavbAzu/Eel8HNngMEXmq7NRYPVioxgZKEiu7Vlx6WSLL2tkTnDqafCZk4ymyhazB3pTbBLkd36RD9C1mciH+PCaoEtkUpWG+OTu0iuB7QoV8tbsjsbvCPwkeoq4Q5u8+YvK8LPPF5VEJn04P12IwBUlJc2civ/36tMtO6H1yvWSRMYByzztAsKyUMvmzc0V4D4vP/i7GwTgtey4QtguOKqbJcHSVHchfdZCkwJdU5XFr4R7u6/R+ZnVf7abHrKyt+8OqHrALrYDq5ZCfGlindtFFS1oBWw9brp+Yx3s60oCIY32sBc5wDT6PxLB8z1zSFAjF2S8sDLkiYBy36j20zVJNwdSz9RPiFo=
