version: '2'

services:
  web:
    image: iide/pmt:latest
    restart: always
    ports:
      - "8000:8000"
  db:
    image: mvertes/alpine-mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
